// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

namespace WebApp.Migrations
{
    [DbContext(typeof(ImageDBContext))]
    [Migration("20210531083238_SettingData")]
    partial class SettingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("WebApp.Data.SettingData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("blur")
                        .HasColumnType("REAL");

                    b.Property<int>("bottom")
                        .HasColumnType("INTEGER");

                    b.Property<double>("brightness")
                        .HasColumnType("REAL");

                    b.Property<double>("contrast")
                        .HasColumnType("REAL");

                    b.Property<double>("fontsize")
                        .HasColumnType("REAL");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("image_format")
                        .HasColumnType("TEXT");

                    b.Property<int>("left")
                        .HasColumnType("INTEGER");

                    b.Property<int>("right")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rotate_x")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rotate_y")
                        .HasColumnType("INTEGER");

                    b.Property<int>("rotate_z")
                        .HasColumnType("INTEGER");

                    b.Property<double>("saturate")
                        .HasColumnType("REAL");

                    b.Property<int>("sepia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .HasColumnType("TEXT");

                    b.Property<int>("text_x")
                        .HasColumnType("INTEGER");

                    b.Property<int>("text_y")
                        .HasColumnType("INTEGER");

                    b.Property<string>("textcolor")
                        .HasColumnType("TEXT");

                    b.Property<int>("top")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("imageData");
                });
#pragma warning restore 612, 618
        }
    }
}
